spring.application.name=Personal-Expense-Traker

server.port=${PORT:8080}
spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=mysql://root:VUkNFxlPOpSDOljLlgFuUtUEzKLEdIkw@metro.proxy.rlwy.net:27364/railway
#jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=true&requireSSL=true
#jdbc:mysql://localhost:3306/ExpenseTracker
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=VUkNFxlPOpSDOljLlgFuUtUEzKLEdIkw
#spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.security.user.name=Aditya13
spring.security.user.password=Aditya13@2005
